# itla_qna.py

questions_and_answers = {
    "¿Qué es el ITLA?": "El ITLA es el Instituto Tecnológico de las Américas.",
    "¿Qué significa ITLA?": "El ITLA es el Instituto Tecnológico de las Américas.",
    "¿Qué es el Instituto Tecnológico de las Américas?": "El ITLA es el Instituto Tecnológico de las Américas.",
    "¿Dónde está ubicado el ITLA?": "El ITLA está ubicado en la calle 23 número 123.",
    "¿Cuál es la dirección del ITLA?": "El ITLA está ubicado en la calle 23 número 123.",
    "¿Dónde se encuentra el ITLA?": "El ITLA está ubicado en la calle 23 número 123.",
    "¿Qué carreras ofrece el ITLA?": "El ITLA ofrece carreras en tecnología, diseño y manufactura.",
    "¿Qué programas académicos tiene el ITLA?": "El ITLA ofrece carreras en tecnología, diseño y manufactura.",
    "¿Qué cursos se pueden estudiar en el ITLA?": "El ITLA ofrece carreras en tecnología, diseño y manufactura.",
    "¿Cuáles son los requisitos de admisión del ITLA?": "Los requisitos de admisión del ITLA incluyen un título de bachiller y pasar un examen de ingreso.",
    "¿Qué necesito para entrar al ITLA?": "Los requisitos de admisión del ITLA incluyen un título de bachiller y pasar un examen de ingreso.",
    "¿Cuáles son las condiciones para ser admitido en el ITLA?": "Los requisitos de admisión del ITLA incluyen un título de bachiller y pasar un examen de ingreso.",
    "¿Cuál es la misión del ITLA?": "La misión del ITLA es formar profesionales altamente capacitados en tecnología.",
    "¿Cuál es el objetivo del ITLA?": "La misión del ITLA es formar profesionales altamente capacitados en tecnología.",
    "¿Para qué fue creado el ITLA?": "La misión del ITLA es formar profesionales altamente capacitados en tecnología.",
    "¿El ITLA ofrece becas?": "Sí, el ITLA ofrece becas para estudiantes destacados.",
    "¿Hay becas disponibles en el ITLA?": "Sí, el ITLA ofrece becas para estudiantes destacados.",
    "¿Cómo puedo obtener una beca en el ITLA?": "Sí, el ITLA ofrece becas para estudiantes destacados.",
    "¿Cuánto cuesta estudiar en el ITLA?": "El costo de estudiar en el ITLA varía según el programa, pero la matrícula general es de $10,000 por semestre.",
    "¿Cuál es la matrícula del ITLA?": "El costo de estudiar en el ITLA varía según el programa, pero la matrícula general es de $10,000 por semestre.",
    "¿Cuáles son los costos de los programas del ITLA?": "El costo de estudiar en el ITLA varía según el programa, pero la matrícula general es de $10,000 por semestre.",
    "¿El ITLA tiene educación a distancia?": "Sí, el ITLA ofrece educación a distancia y cursos en línea.",
    "¿Hay clases en línea en el ITLA?": "Sí, el ITLA ofrece educación a distancia y cursos en línea.",
    "¿El ITLA ofrece cursos virtuales?": "Sí, el ITLA ofrece educación a distancia y cursos en línea.",
    "¿Cómo puedo contactar al ITLA?": "Puedes contactar al ITLA a través de su página web o llamando al número 555-1234.",
    "¿Dónde puedo comunicarme con el ITLA?": "Puedes contactar al ITLA a través de su página web o llamando al número 555-1234.",
    "¿Cuál es el número de teléfono del ITLA?": "Puedes contactar al ITLA a través de su página web o llamando al número 555-1234.",
    "¿Quién es el rector del ITLA?": "El rector del ITLA es el Dr. Juan Pérez.",
    "¿Quién dirige el ITLA?": "El rector del ITLA es el Dr. Juan Pérez.",
    "¿Quién está a cargo del ITLA?": "El rector del ITLA es el Dr. Juan Pérez."
}